// Bölgeler. Yalnızca veri — mantık kodu yok.
// Bölgeler `sira` alanına göre sırayla açılır (plan.md Bölüm 4).
// `giris` ve `bossIli` il plakasıdır, `boss` dusmanlar.js anahtarıdır.
// `miniBoss` bölgenin mini bossu, `miniBossIlleri` onun ortaya çıktığı illerdir
// (ilin arınması %50'yi geçince, plan.md Faz 7).
// `ahiIlleri`: Ahi esnafının silah ve zırh dükkânı olan iller (her 3–4 ilde bir).
// `kervansarayIlleri`: dinlenilen, bayılınca dönülen ve hızlı yolculuk yapılan iller.
// `yemekCarpani`, yöresel yemeklerin güç ve fiyat çarpanıdır (plan.md Bölüm 7).

export const bolgeler = [
  {
    anahtar: 'marmara',
    ad: 'Marmara',
    sira: 1,
    seviye: [1, 10],
    giris: 34,
    boss: 'bogaz_ejderi',
    bossIli: 34,
    miniBoss: 'gulyabani',
    miniBossIlleri: [16, 22],
    ahiIlleri: [34, 16, 22],
    kervansarayIlleri: [34, 17],
    renk: '#2aa7a7',
    yemekCarpani: 1.0,
  },
  {
    anahtar: 'ege',
    ad: 'Ege',
    sira: 2,
    seviye: [8, 18],
    giris: 45,
    boss: 'yelbegen',
    bossIli: 35,
    miniBoss: 'carsamba_karisi',
    miniBossIlleri: [20, 48],
    ahiIlleri: [45, 20],
    kervansarayIlleri: [45, 48],
    renk: '#3b7dc4',
    yemekCarpani: 1.5,
  },
  {
    anahtar: 'akdeniz',
    ad: 'Akdeniz',
    sira: 3,
    seviye: [15, 25],
    giris: 7,
    boss: 'sahmeran',
    bossIli: 33,
    miniBoss: 'yilan_beyi',
    miniBossIlleri: [1, 32],
    ahiIlleri: [7, 1],
    kervansarayIlleri: [7, 1],
    renk: '#d9483b',
    yemekCarpani: 2.2,
  },
  {
    anahtar: 'ic_anadolu',
    ad: 'İç Anadolu',
    sira: 4,
    seviye: [20, 32],
    giris: 42,
    boss: 'albasti',
    bossIli: 50,
    miniBoss: 'golge_albasti',
    miniBossIlleri: [38, 58],
    ahiIlleri: [42, 6, 38, 58],
    kervansarayIlleri: [42, 68, 58],
    renk: '#d4a537',
    yemekCarpani: 3.0,
  },
  {
    anahtar: 'karadeniz',
    ad: 'Karadeniz',
    sira: 5,
    seviye: [28, 40],
    giris: 14,
    boss: 'karakoncolos',
    bossIli: 61,
    miniBoss: 'yayla_devi',
    miniBossIlleri: [37, 53],
    ahiIlleri: [14, 37, 55, 61, 53],
    kervansarayIlleri: [14, 55, 61],
    renk: '#7b5236',
    yemekCarpani: 4.0,
  },
  {
    anahtar: 'guneydogu',
    ad: 'Güneydoğu Anadolu',
    sira: 6,
    seviye: [35, 45],
    giris: 27,
    boss: 'tepegoz',
    bossIli: 63,
    miniBoss: 'tepegozun_muhafizi',
    miniBossIlleri: [21, 47],
    ahiIlleri: [27, 63, 47],
    kervansarayIlleri: [27, 21],
    renk: '#c9772f',
    yemekCarpani: 5.0,
  },
  {
    anahtar: 'dogu_anadolu',
    ad: 'Doğu Anadolu',
    sira: 7,
    seviye: [42, 50],
    giris: 44,
    boss: 'van_golu_canavari',
    bossIli: 65,
    miniBoss: 'tipi_ifriti',
    miniBossIlleri: [25, 36],
    ahiIlleri: [44, 25, 36, 65],
    kervansarayIlleri: [44, 25, 65],
    renk: '#6a4c93',
    yemekCarpani: 6.0,
  },
];

// Final savaşı: Ağrı Dağı'ndaki kalede Zülmet (plan.md Faz 10).
// Kale, `onkosulBolge` bölgesinin bossu yenilip oyuncu `seviye`ye ulaşınca açılır.
export const final = {
  boss: 'zulmet',
  il: 4,
  seviye: 48,
  onkosulBolge: 'dogu_anadolu',
  dusmanSeviyesi: 50,
};
