// Görevler (plan.md Faz 9). Yalnızca veri — mantık kodu yok.
// Görevleri köy muhtarları ve Ahi Babalar verir. Her bölgede dört görev vardır.
//
// il: görevi veren kişinin ili (plaka). veren: 'muhtar' | 'ahi_baba'
//   (Ahi Babalar yalnızca Ahi esnafı olan illerde bulunur).
// tur:
//   'yen'      → `dusman` türünden `sayi` tane yen (görev alındıktan sonra, herhangi bir ilde).
//   'arindir'  → `hedefIl` ilini en az %`yuzde` arındır.
//   'ulastir'  → veren kişinin verdiği `yemek`i `hedefIl` ilinin muhtarına ulaştır.
// anlatim: görevi verenin sözleri. tesekkur: görev bitince söylenen sözler
//   (ulaştırma görevlerinde yemeği teslim alan muhtarın).
// Yeni ya da ulaştırılacak yemekler için yemekler.js, düşmanlar için dusmanlar.js anahtarları.

export const GOREV_TURLERI = ['yen', 'arindir', 'ulastir'];
export const GOREV_VERENLER = ['muhtar', 'ahi_baba'];

export const gorevler = {
  // ── Marmara ──────────────────────────────────────────────
  bostanlarin_bekcisi: {
    ad: 'Bostanların Bekçisi',
    bolge: 'marmara',
    il: 34,
    veren: 'muhtar',
    tur: 'yen',
    dusman: 'ac_kurt',
    sayi: 3,
    anlatim: 'Yiğidim, aç kurtlar gece gece bostanlarımıza iniyor; bostancılar tarlaya çıkamaz oldu. Üç tanesini şehirden uzaklaştırırsan mahallemiz rahat bir uyku uyur.',
    tesekkur: 'Eline, yüreğine sağlık! Bostancılar sabah erkenden tarlaya çıktı, mahallede herkes senin adını anıyor.',
  },
  komsuya_pismaniye: {
    ad: 'Komşuya Pişmaniye',
    bolge: 'marmara',
    il: 41,
    veren: 'muhtar',
    tur: 'ulastir',
    yemek: 'pismaniye',
    hedefIl: 54,
    anlatim: 'Sakarya\'daki muhtar komşumuz geçen kış bize çok yardım etmişti. Şu pişmaniyeyi ona götürür müsün? Yollar tehlikeli, emin ellere vermek istiyorum.',
    tesekkur: 'Kocaeli\'den pişmaniye mi? Komşuluk böyle olur işte! Getirdiğin için sağ ol yiğidim.',
  },
  aycicegi_tarlalari: {
    ad: 'Ayçiçeği Tarlaları',
    bolge: 'marmara',
    il: 59,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 59,
    yuzde: 70,
    anlatim: 'Ayçiçekleri güneşe dönmeyi unuttu; Zülmet\'in sihri tarlalarımızın üstüne gölge gibi çöktü. İlimizi arındırırsan hasat yeniden bereketlenir.',
    tesekkur: 'Bak, ayçiçekleri yeniden güneşe döndü! Hasat şenliğinin baş konuğu sensin.',
  },
  ipek_kervani: {
    ad: 'İpek Kervanı',
    bolge: 'marmara',
    il: 16,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'yol_kesen_cin',
    sayi: 4,
    anlatim: 'Evlat, hana gelecek ipek kervanları yolda kalıyor. Yol kesen cinler dokumacılarımızın emeğini çalıyor. Onları dağıtırsan esnafımız sana minnettar kalır.',
    tesekkur: 'Kervanlar hana vardı, tezgâhlar yeniden işliyor. Ahilik yardımlaşmadır; bugün sen bizim yükümüzü taşıdın.',
  },

  // ── Ege ──────────────────────────────────────────────────
  mesir_macunu: {
    ad: 'Mesir Macunu',
    bolge: 'ege',
    il: 45,
    veren: 'ahi_baba',
    tur: 'ulastir',
    yemek: 'mesir_macunu',
    hedefIl: 35,
    anlatim: 'Mesir macunumuzu kırk bir baharatla, sabırla karar hazırlarız. İzmir muhtarına bir kavanoz söz vermiştim; yollar kapanınca gönderemedim. Sen götürür müsün evlat?',
    tesekkur: 'Manisa\'nın mesiri gelmiş! Kokusu bütün mahalleyi sardı. Eksik olma yiğidim.',
  },
  incir_bahceleri: {
    ad: 'İncir Bahçeleri',
    bolge: 'ege',
    il: 9,
    veren: 'muhtar',
    tur: 'yen',
    dusman: 'yaban_domuzu',
    sayi: 4,
    anlatim: 'Sihirle azmış yaban domuzları incir bahçelerimizi talan ediyor, ağaçların dibini eşeliyor. Onları bahçelerden uzaklaştırırsan bu yaz incirimiz dalında olgunlaşır.',
    tesekkur: 'Bahçeler kurtuldu, incirler dalında ballanıyor. Emeğine sağlık yiğidim!',
  },
  cini_firinlari: {
    ad: 'Çini Fırınları',
    bolge: 'ege',
    il: 43,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 43,
    yuzde: 80,
    anlatim: 'Çini ustalarımızın fırınları soğudu; Zülmet\'in sihri renkleri soldurdu, desenler tutmuyor. İlimizi arındırırsan fırınlar yeniden yanar.',
    tesekkur: 'Fırınlar yandı; lacivert yeniden lacivert, turkuaz yeniden turkuaz! Ustalar ilk tabağı senin şerefine boyadı.',
  },
  dokumaci_tezgahi: {
    ad: 'Dokumacıların Tezgâhı',
    bolge: 'ege',
    il: 20,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'kara_cin',
    sayi: 4,
    anlatim: 'Kara cinler gece atölyelere giriyor, tezgâhların ipliğini dolaştırıyor. Dokumacılarımız sabah işe başlıyor, akşam her şey karmakarışık. Onları dağıtır mısın evlat?',
    tesekkur: 'Tezgâhlar yeniden şakır şakır işliyor. Ahi kardeşlerimiz seni hep hayırla anacak.',
  },

  // ── Akdeniz ──────────────────────────────────────────────
  portakal_bahceleri: {
    ad: 'Portakal Bahçeleri',
    bolge: 'akdeniz',
    il: 7,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'akrep_surusu',
    sayi: 4,
    anlatim: 'Akrep sürüleri bahçelere yayıldı, işçiler portakal toplamaya korkuyor. Onları dağıtırsan meyveler dalda kalmaz, çarşıya iner.',
    tesekkur: 'Bahçelerde yine türküler söyleniyor, sepetler dolu. Sağ olasın evlat.',
  },
  gul_serbeti: {
    ad: 'Gül Şerbeti',
    bolge: 'akdeniz',
    il: 32,
    veren: 'muhtar',
    tur: 'ulastir',
    yemek: 'gul_serbeti',
    hedefIl: 15,
    anlatim: 'Gül bahçelerimizden süzdüğümüz şerbeti Burdur\'daki komşularımıza götürür müsün? Gül zamanı onlara hep bir testi yollarız; bu yıl yollar kapalı kaldı.',
    tesekkur: 'Isparta\'nın gülü, gönlümüzün şerbeti! Komşularımız bizi unutmamış. Var ol yiğidim.',
  },
  asinin_kiyilari: {
    ad: 'Asi\'nin Kıyıları',
    bolge: 'akdeniz',
    il: 31,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 31,
    yuzde: 80,
    anlatim: 'Asi Nehri\'nin kıyıları eskiden şenlik yeriydi; şimdi Zülmet\'in sihri yüzünden kimse suya yaklaşamıyor. İlimizi arındırırsan kıyılar yeniden şenlenir.',
    tesekkur: 'Asi yeniden berrak akıyor, çocuklar kıyıda oynuyor. Sofralarımız sana her zaman açık.',
  },
  toros_yolu: {
    ad: 'Toros Yolu',
    bolge: 'akdeniz',
    il: 1,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'anadolu_parsi',
    sayi: 3,
    anlatim: 'Yörükler sürülerini Toros yaylalarına çıkaramıyor; sihirle azmış parslar yolu tutmuş. Onları yoldan uzaklaştırırsan göç yeniden başlar.',
    tesekkur: 'Sürüler yaylaya çıktı, çan sesleri dağlara yayıldı. Yörük kardeşlerimiz sana selam yolladı.',
  },

  // ── İç Anadolu ───────────────────────────────────────────
  firindan_karamana: {
    ad: 'Fırından Karaman\'a',
    bolge: 'ic_anadolu',
    il: 42,
    veren: 'ahi_baba',
    tur: 'ulastir',
    yemek: 'etli_ekmek',
    hedefIl: 70,
    anlatim: 'Fırından yeni çıkan etli ekmeği Karaman\'daki kardeşimize götür evlat. Kış boyu buğdayını bizden esirgemedi; biz de sofrasını boş bırakmayalım.',
    tesekkur: 'Konya\'nın etli ekmeği hâlâ sıcak! Kardeşlik böyle yaşar. Eline sağlık yiğidim.',
  },
  porsugun_kiyisi: {
    ad: 'Porsuk\'un Kıyısı',
    bolge: 'ic_anadolu',
    il: 26,
    veren: 'muhtar',
    tur: 'yen',
    dusman: 'toz_ifriti',
    sayi: 4,
    anlatim: 'Toz ifritleri Porsuk Çayı\'nın kıyısını toza boğdu; bahçeler kurudu, çocuklar dışarı çıkamıyor. Onları dağıtırsan kıyımız yeniden yeşerir.',
    tesekkur: 'Porsuk yeniden pırıl pırıl akıyor, bahçeler yeşerdi. Sağ olasın yiğidim.',
  },
  bozkirin_turkusu: {
    ad: 'Bozkırın Türküsü',
    bolge: 'ic_anadolu',
    il: 40,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 40,
    yuzde: 80,
    anlatim: 'Bizim ilin bağlaması hiç susmazdı yiğidim; Zülmet\'in sihri çöktüğünden beri kimsenin türkü söyleyecek hâli yok. İlimizi arındırırsan bozkır yeniden türküsüne kavuşur.',
    tesekkur: 'Duyuyor musun? Bozkırın rüzgârı yeniden türkü taşıyor. Bu türküyü senin için yaktılar.',
  },
  erciyes_yolu: {
    ad: 'Erciyes Yolu',
    bolge: 'ic_anadolu',
    il: 38,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'bozkir_kurdu',
    sayi: 4,
    anlatim: 'Esnafımız sözüne sadıktır evlat, ama yollar kesilince söz tutmak zorlaşıyor. Bozkır kurtları kervan yolunu tuttu; onları uzaklaştırırsan mallar vaktinde yerine ulaşır.',
    tesekkur: 'Kervanlar vaktinde vardı, sözümüzü tuttuk. Ahi esnafı iyiliği unutmaz.',
  },

  // ── Karadeniz ────────────────────────────────────────────
  cay_yolu: {
    ad: 'Çay Yolu',
    bolge: 'karadeniz',
    il: 53,
    veren: 'ahi_baba',
    tur: 'ulastir',
    yemek: 'rize_cayi',
    hedefIl: 8,
    anlatim: 'Bu yılın ilk çayını Artvin\'deki kardeşlerimize yollayacaktık; sis çöktü, yol kapandı. Şu paketi Artvin muhtarına ulaştırır mısın evlat?',
    tesekkur: 'Rize\'nin taze çayı! Demleyelim de hep beraber içelim. Yolun açık olsun yiğidim.',
  },
  kiyidaki_sis: {
    ad: 'Kıyıdaki Sis',
    bolge: 'karadeniz',
    il: 57,
    veren: 'muhtar',
    tur: 'yen',
    dusman: 'sis_cini',
    sayi: 4,
    anlatim: 'Sis cinleri limanı kapladı; balıkçılar denize açılamıyor, kayıklar kıyıyı göremiyor. Onları dağıtırsan ufuk yeniden görünür.',
    tesekkur: 'Sis dağıldı, fener yeniden ufka ışık saçıyor. Balıkçılar seni sofralarına davet ediyor.',
  },
  findik_hasadi: {
    ad: 'Fındık Hasadı',
    bolge: 'karadeniz',
    il: 52,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 52,
    yuzde: 80,
    anlatim: 'Fındık toplama vakti geldi ama bahçeler Zülmet\'in sihriyle karardı; imece kurulamıyor. İlimizi arındırırsan bütün köy bahçeye çıkar.',
    tesekkur: 'İmece kuruldu, yamaçlar şenlendi! Bu yılın ilk fındığı senin hakkın.',
  },
  ari_kovanlari: {
    ad: 'Arı Kovanları',
    bolge: 'karadeniz',
    il: 55,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'boz_ayi',
    sayi: 3,
    anlatim: 'Sihirle azmış boz ayılar arıcılarımızın kovanlarını deviriyor. Onları dağlara geri gönderirsen bal mevsimi kurtulur.',
    tesekkur: 'Kovanlar yerinde, arılar çiçekte. Arıcılar sana selam ve teşekkür yolladı.',
  },

  // ── Güneydoğu Anadolu ────────────────────────────────────
  kirk_kat_baklava: {
    ad: 'Kırk Kat Baklava',
    bolge: 'guneydogu',
    il: 27,
    veren: 'ahi_baba',
    tur: 'ulastir',
    yemek: 'antep_baklavasi',
    hedefIl: 79,
    anlatim: 'Ustalarımız kırk kat yufkayla bir tepsi baklava açtı; Kilis\'teki kardeşlerimizin şenliğine yetişmesi lazım. Götürür müsün evlat?',
    tesekkur: 'Antep\'in baklavası şenliğimize yetişti! Kardeş illerin sofrası bir olur. Sağ ol yiğidim.',
  },
  kahta_cayi: {
    ad: 'Kâhta Çayı',
    bolge: 'guneydogu',
    il: 2,
    veren: 'muhtar',
    tur: 'yen',
    dusman: 'kum_ifriti',
    sayi: 4,
    anlatim: 'Kum ifritleri Kâhta Çayı\'nın yatağını kumla dolduruyor, tarlalar susuz kaldı. Onları dağıtırsan su yeniden tarlaya akar.',
    tesekkur: 'Çay yeniden akıyor, tarlalar suya kandı. Eline sağlık yiğidim.',
  },
  dicle_kiyisi: {
    ad: 'Dicle Kıyısı',
    bolge: 'guneydogu',
    il: 72,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 72,
    yuzde: 80,
    anlatim: 'Dicle kıyısındaki köylerimiz Zülmet\'in sihrinden bunaldı; çiftçiler tarlaya, çobanlar meraya çıkamıyor. İlimizi arındırırsan ova yeniden nefes alır.',
    tesekkur: 'Dicle yeniden türküsünü söylüyor, ova bereketlendi. Yolun hep açık olsun.',
  },
  tas_ustalari: {
    ad: 'Taş Ustaları',
    bolge: 'guneydogu',
    il: 47,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'tas_dev',
    sayi: 3,
    anlatim: 'Evlerimiz sarı taştan, sabırla oyulur. Sihirle azmış taş devler ocaklarımızı yıkıyor, ustalarımız taş kesemiyor. Onları uzaklaştır evlat.',
    tesekkur: 'Ocaklar yeniden açıldı, keskiler taşa işliyor. İyiliğini taşa işler gibi hatırlayacağız.',
  },

  // ── Doğu Anadolu ─────────────────────────────────────────
  kayisi_yolu: {
    ad: 'Kayısı Yolu',
    bolge: 'dogu_anadolu',
    il: 44,
    veren: 'ahi_baba',
    tur: 'ulastir',
    yemek: 'malatya_kayisisi',
    hedefIl: 23,
    anlatim: 'Güneşte kurutulmuş en güzel kayısılarımızı Elazığ\'daki komşumuza söz verdim. Yollar karlı, cinler tetikte; bu heybeyi ancak sen ulaştırırsın.',
    tesekkur: 'Malatya\'nın kayısısı tatlı, komşuluğu daha da tatlı! Getirdiğin için sağ ol yiğidim.',
  },
  yayla_suruleri: {
    ad: 'Yayla Sürüleri',
    bolge: 'dogu_anadolu',
    il: 24,
    veren: 'muhtar',
    tur: 'yen',
    dusman: 'karli_dag_kurdu',
    sayi: 4,
    anlatim: 'Karlı dağ kurtları sürülerimize dadandı; çobanlar yaylaya çıkamıyor, tulum peynirimiz mayalanamıyor. Onları uzaklaştırırsan sürüler güvende olur.',
    tesekkur: 'Sürüler yaylada, çobanlar kavalını çalıyor. Bütün köy sana selam yolladı.',
  },
  mus_ovasi: {
    ad: 'Muş Ovası',
    bolge: 'dogu_anadolu',
    il: 49,
    veren: 'muhtar',
    tur: 'arindir',
    hedefIl: 49,
    yuzde: 80,
    anlatim: 'Baharda ovamız lalelerle kızıla boyanırdı; bu yıl Zülmet\'in sihri yüzünden tek lale açmadı. İlimizi arındırırsan ova yeniden çiçeğe durur.',
    tesekkur: 'Laleler açtı, ova yeniden kızıla boyandı! Bu baharı sana borçluyuz.',
  },
  mandira_yolu: {
    ad: 'Mandıra Yolu',
    bolge: 'dogu_anadolu',
    il: 36,
    veren: 'ahi_baba',
    tur: 'yen',
    dusman: 'zulmetin_muhafizi',
    sayi: 3,
    anlatim: 'Zülmet\'in muhafızları yayla yolunu kesti; peynircilerimiz sütü mandıraya indiremiyor. Onları dağıtırsan mandıralar yeniden çalışır.',
    tesekkur: 'Süt mandıraya indi, peynirler rafa dizildi. Ahi esnafı sana minnettar evlat.',
  },
};
