// Arayüz metinleri tek yerde. Yalnızca veri — mantık kodu yok.
// {ad} biçimindeki yer tutucular arayüzde doldurulur (bilesenler.js → sablon).

export const metinler = {
  oyunAdi: 'Seksen Bir Diyar',
  altBaslik: 'Zülmet\'in sihrine karşı yiğitçe bir yolculuk',
  giris:
    'Zalim sihirbaz Zülmet, yasak sihirle cinleri ve ifritleri Anadolu\'ya saldı. ' +
    'Yollar kesildi, kervanlar yağmalandı. Mazlumu korumak için bir yiğit yola çıkıyor.',

  baslik: {
    devamEt: 'Devam Et',
    yeniOyun: 'Yeni Oyun',
    kayitOzeti: '{ad} · {sinif} · Sv {seviye} · {il}',
    yeniOyunUyarisi: 'Kayıtlı yolculuğun silinecek. Yeni bir oyuna başlamak istediğine emin misin?',
    evet: 'Evet, yeni oyuna başla',
    vazgec: 'Vazgeç',
    kayitYapilamiyor: 'Tarayıcın kayda izin vermiyor; sayfayı kapatınca ilerlemen kaybolur.',
  },

  ilEkrani: {
    haritayaDon: 'Haritaya dön',
    kesfeCik: 'Keşfe Çık',
    heybe: 'Heybe',
    karakter: 'Karakter',
    seviye: 'Düşman seviyesi',
    yemek: 'Meşhur yemeği',
    arinma: 'Arınma',
    arinmaIpucu: 'Her zafer ili %8–12 arındırır. %100 olunca il arınmış sayılır.',
    arinmis: '✓ Bu il Zülmet\'in sihrinden arındı. Keşfe çıkıp tecrübe kazanmaya devam edebilirsin.',
    canAz: 'Canın azaldı. Keşfe çıkmadan önce heybenden bir şeyler yiyebilirsin.',
    akce: '{akce} akçe',
  },

  envanter: {
    baslik: 'Heybe',
    geri: 'Geri dön',
    yuva: '{dolu} / {toplam} yuva',
    bos: 'Heyben boş. Düşmanları yendikçe illerin yöresel yemeklerini toplarsın.',
    ye: 'Ye',
    etki: '+{miktar} {tur}',
    doluCan: 'Canın zaten dolu.',
    doluNefes: 'Nefesin zaten dolu.',
    yedin: '{yemek} yedin: +{miktar} {tur}.',
    yeAciklama: '{yemek} ye',
  },

  harita: {
    baslikEkrani: 'Başlık ekranına dön',
    konum: 'Bulunduğun il',
    yakinlastir: 'Yakınlaştır',
    uzaklastir: 'Uzaklaştır',
    ortala: 'Bulunduğun ile odaklan',
    tumu: 'Tüm haritayı göster',
    bolge: 'Bölge',
    seviye: 'Düşman seviyesi',
    seviyeDegeri: 'Sv {en_az}–{en_cok}',
    yemek: 'Meşhur yemeği',
    arinma: 'Arınma',
    buradasin: 'Buradasın.',
    git: 'Buraya git',
    kapat: 'Kapat',
    ileGir: 'İl ekranına git',
    varis: 'Yeni konum: {il}',
    ipucu: 'Bir ile dokunarak bilgilerini gör. Parmağınla kaydır, iki parmakla yakınlaştır.',
    lejant: {
      kilitli: 'Kilitli',
      acik: 'Açık',
      bulunulan: 'Bulunduğun il',
      arinmis: 'Arınmış',
    },
    denizler: {
      karadeniz: 'Karadeniz',
      akdeniz: 'Akdeniz',
      ege: 'Ege Denizi',
      marmara: 'Marmara',
    },
  },

  statAdlari: {
    can: 'Can',
    nefes: 'Nefes',
    guc: 'Güç',
    savunma: 'Savunma',
    ceviklik: 'Çeviklik',
  },

  dusmanTurleri: {
    hayvan: 'Hayvan',
    cin: 'Cin',
    ifrit: 'İfrit',
    hortlak: 'Hortlak',
    dev: 'Dev',
    boss: 'Boss',
  },

  yeniOyun: {
    baslik: 'Yeni Oyun',
    geri: 'Başlık ekranına dön',
    adEtiketi: 'Yiğidin adı',
    adIpucu: 'Boş bırakırsan adın Alp olur.',
    sinifBasligi: 'Yolunu seç',
    sinifSec: '{sinif} sınıfını seç',
    secimYok: 'Yola çıkmak için bir sınıf seç.',
    baslat: 'Yola Çık',
  },

  karakter: {
    baslik: 'Karakter',
    geri: 'Geri dön',
    seviye: 'Sv {seviye}',
    xp: 'Tecrübe (XP)',
    xpDegeri: '{xp} / {gereken} XP',
    statlar: 'Statlar',
    statPuani: 'Dağıtılacak stat puanı: {puan}',
    statPuaniYok: 'Seviye atladıkça dağıtabileceğin stat puanları kazanırsın.',
    puanVer: '{stat} statına 1 puan ver (+{artis})',
    yetenekler: 'Yetenekler',
    yetenekNefes: '{nefes} nefes',
    yetenekKilitli: 'Sv {seviye} olunca açılır',
    akce: 'Akçe',
    ustCubukDugmesi: 'Karakteri aç: {ad}, seviye {seviye}',
  },

  savas: {
    baslik: 'Savaş',
    seviye: 'Sv {seviye}',
    saldir: 'Saldır',
    yetenek: 'Yetenek',
    yemek: 'Yemek',
    kac: 'Kaç',
    geri: 'Geri',
    heybeBos: 'Heybende yemek yok.',
    kacilamaz: 'Bu mahlûktan kaçılamaz.',
    nefesYetersiz: 'Nefesin yetmiyor.',
    etkiler: {
      savunma: '🛡️ Korunma ({kalan})',
      guclenme: '💪 Güç ({kalan})',
      kritik: '🦅 Keskin göz ({kalan})',
      zayiflatma: '😨 Ürkmüş ({kalan})',
    },
    gunluk: {
      baslangic: '{ikon} {dusman} (Sv {seviye}) yolunu kesti!',
      saldiri: 'Saldırdın: {hasar} hasar.',
      yetenekHasar: '{yetenek}: {hasar} hasar.',
      kritik: 'Kritik vuruş!',
      ekHasar: 'Sihri sarsıldı!',
      dusmanKacindi: '{dusman} hamlenden sıyrıldı.',
      yetenekSifa: '{yetenek}: {miktar} can toparladın.',
      yetenekSavunma: '{yetenek}: düşmanın sonraki {sure} hamlesinde daha az hasar alacaksın.',
      yetenekGuclenme: '{yetenek}: sonraki {sure} saldırın daha güçlü olacak.',
      yetenekKritik: '{yetenek}: sonraki {sure} saldırında kritik vuruş şansın arttı.',
      yemek: '{yemek} yedin: {miktar} {tur} yeniledin.',
      dusmanSaldiri: '{dusman} saldırdı: {hasar} hasar aldın.',
      ozelHamle: '{dusman} — {hamle}! {hasar} hasar aldın.',
      zayiflatma: '{dusman} — {hamle}! Sonraki {sure} saldırında gücün azalacak.',
      oyuncuKacindi: '{dusman} saldırdı ama hamleden ustalıkla sıyrıldın.',
      ozelKacindi: '{dusman} — {hamle}! Ama hamleden ustalıkla sıyrıldın.',
      korundu: 'Duruşun hasarı azalttı.',
      kacisBasarili: 'Geri çekilip yoluna devam ettin.',
      kacisBasarisiz: 'Kaçamadın! {dusman} yolunu kesti.',
      yenilgi: 'Gözlerin karardı, bayıldın…',
    },
    // Yenilen düşmanlar ölmez: kaçar, dağılır ya da sihri bozulur (plan.md Bölüm 2).
    dagilma: {
      hayvan: '{dusman} geri çekilip kaçtı.',
      cin: '{dusman} üzerindeki sihir bozuldu, dağılıp gitti.',
      ifrit: '{dusman} üzerindeki sihir bozuldu, dumana dönüşüp dağıldı.',
      hortlak: '{dusman} sisin içinde dağılıp kayboldu.',
      dev: '{dusman} üzerindeki sihir bozuldu; sessizce çekip gitti.',
      boss: '{dusman} üzerindeki sihir bozuldu!',
    },
    sonuc: {
      zafer: 'Zafer!',
      yenilgi: 'Bayıldın',
      kacis: 'Geri Çekildin',
      xp: '+{xp} XP kazandın.',
      bayilma: '{il} merkezinde kendine geldin. Halk seni misafir etti; canın ve nefesin yerine geldi.',
      akceKaybi: 'Kesenden {akce} akçe düşmüş.',
      kacis: 'Canını kurtardın; bu karşılaşmadan ödül yok.',
      seviyeAtladin: '🎉 Seviye atladın! Artık Sv {seviye}.',
      statPuaniKazandin: 'Dağıtılacak {puan} stat puanın var.',
      yeniYetenek: '✨ Yeni yetenek: {yetenek}',
      arinma: 'İl %{artis} arındı (şimdi %{yuzde}).',
      arindi: '🌿 {il} Zülmet\'in sihrinden tamamen arındı!',
      akce: '+{akce} akçe kazandın.',
      yemek: '{ikon} {yemek} buldun!',
      yemekSigmadi: '{ikon} {yemek} buldun ama heyben dolu, yanına alamadın.',
      devam: 'Devam et',
      karakteriAc: 'Karakterine bak',
    },
  },

  seyahatEngeli: {
    ayni_il: 'Zaten buradasın.',
    kilitli_bolge: '{bolge} bölgesi henüz kilitli. Yollar Zülmet\'in sihriyle kapalı.',
    komsu_degil: '{hedef}, bulunduğun il {konum} ile komşu değil. Yalnızca komşu illere gidebilirsin.',
  },
};
