// Arayüz metinleri tek yerde. Yalnızca veri — mantık kodu yok.
// {ad} biçimindeki yer tutucular arayüzde doldurulur (bilesenler.js → sablon).

export const metinler = {
  oyunAdi: 'Seksen Bir Diyar',
  altBaslik: 'Zülmet\'in sihrine karşı yiğitçe bir yolculuk',
  giris:
    'Zalim sihirbaz Zülmet, yasak sihirle cinleri ve ifritleri Anadolu\'ya saldı. ' +
    'Yollar kesildi, kervanlar yağmalandı. Mazlumu korumak için bir yiğit yola çıkıyor.',

  // Haritada dolaşan ya da yürürken bir anda önüne çıkan boss yaratıklar
  gezginBoss: {
    rozet: 'Gezgin boss',
    surprizRozet: 'Sürpriz boss',
    tehlike: { zorlu: '⚔️ Zorlu', kesilemez: '💀 Kesilemez' },
    tehlikeAciklama: {
      zorlu: 'Bu diyarın düşmanlarından güçlü ama kesilebilir',
      kesilemez: 'Kesilemez: zırhına kılıç zor işler, kaçmak gerekebilir',
    },
    surpriz: '⚡ Sürpriz! {dusman} birden önüne çıktı!',
    yenildi: 'Güçlü {dusman} dağılıp gitti!',
  },

  boss: {
    muhurlu: '{boss} mühürlü. Mührü çözmek için {bolge} illerinin ortalama arınması %{gerekenArinma} (şimdi %{arinma}), seviyen de en az {gerekenSeviye} (şimdi {seviye}) olmalı.',
    acildi: 'Mühür çözüldü! {boss} artık {il} ilindeki ininde seni bekliyor.',
    miniBelirdi: '{boss} ortaya çıktı! Bu ildeki ininde seni bekliyor.',
    miniYenildi: '{boss} dağılıp gitti; bu ilin halkı derin bir nefes aldı.',
    sofra: 'Zafer sofrası kuruldu: {yemekler}. Canın ve nefesin doldu; {savas} savaş boyunca gücün %10 arttı.',
    yeniBolge: 'Yeni bölge açıldı: {bolge}. Yolun {il} ilinden geçiyor.',
    rozet: 'Boss',
    miniRozet: 'Mini boss',
    muhurRozeti: 'Mühürlü',
    kartBasligi: 'Bölge bossu',
    durum: {
      muhurlu: 'Mühürlü',
      acik: 'Mührü çözüldü',
      yenildi: 'Yenildi ✓',
    },
    kosul: 'Arınma %{arinma}/%{gerekenArinma} · Sv {seviye}/{gerekenSeviye}',
    sofraDurumu: 'Zafer sofrası: {kalan} savaş boyunca gücün %10 fazla.',
  },

  // Görev verenler ve görevler (plan.md Faz 9).
  gorev: {
    geri: 'Meydana dön',
    verenler: { muhtar: 'Muhtar', ahi_baba: 'Ahi Baba' },
    verenlerCumlede: { muhtar: 'muhtar', ahi_baba: 'Ahi Baba' },
    // Görev verenin selamı; oyuncunun unvanına (itibar kademesine) göre.
    selamlar: {
      muhtar: [
        'Hoş geldin yolcu. Kapımıza gelen misafir başımızın tacıdır.',
        'Hoş geldin yiğidim! Adını duyduk; iyiliğin senden önce gelmiş.',
        'Vay, bizim yiğit gelmiş! Otur hele, bir soluklan.',
        'Halkın yiğidi aramızda! Çocuklar senin hikâyelerini anlatıyor.',
        'Diyarın kahramanı ilimizi şereflendirdi! Buyur, başımızın üstünde yerin var.',
      ],
      ahi_baba: [
        'Hoş geldin evlat. Ahi kapısı yolcuya her zaman açıktır.',
        'Hoş geldin evlat; iyiliğini esnaf arasında konuşuyorlar.',
        'Gel evlat, gel. Senin gibi yiğitler Ahiliğin yüz akıdır.',
        'Halkın yiğidi! Esnafımız seni gördükçe gönlü ferahlıyor.',
        'Diyarın kahramanı, hoş geldin. Kapımız da sofralarımız da sana açık.',
      ],
    },
    bosSoz: {
      muhtar: 'Şimdilik bir derdimiz yok yiğidim. Yolun açık olsun.',
      ahi_baba: 'Şimdilik bir işimiz yok evlat. Hayırlı yolculuklar.',
    },
    gorevler: 'Görevler',
    teslimler: 'Teslim edilecekler',
    kabulEt: 'Kabul et',
    teslimEt: 'Teslim et',
    hedef: {
      yen: 'Yenilecek düşman: {dusman} ({mevcut}/{hedef})',
      arindir: 'Arındırılacak il: {il} (%{mevcut}/%{hedef})',
      ulastir: 'Götürülecek yer: {il} muhtarı ({yemek})',
    },
    yenIpucu: 'Bu düşmana şu illerde rastlanır: {iller}.',
    ulastirIpucu: 'Kabul edersen muhtar sana bir {yemek} verecek.',
    yemekYok: 'Heybende {yemek} kalmadı; {il} arastasında bulabilirsin.',
    hazir: 'Hazır! {il} ilindeki {veren} seni bekliyor.',
    teslimYeri: 'Teslim: {il} · {veren}',
    odul: 'Ödül: {xp} XP · {akce} akçe · {hayir} Hayır',
    durum: {
      alinabilir: 'Yeni',
      aktif: 'Sürüyor',
      hazir: 'Hazır',
      tamam: 'Tamamlandı ✓',
    },
    neden: {
      heybe_dolu: 'Heyben dolu; götüreceğin yemeğe yer aç.',
      hazir_degil: 'Görev henüz bitmedi.',
    },
    kabulEdildi: '"{gorev}" görevini üstlendin.',
    yemekVerildi: '{yemek} heybene kondu.',
    tamamlandi: '"{gorev}" tamamlandı! +{xp} XP, +{akce} akçe, +{hayir} Hayır.',
    hediye: {
      baslik: 'Köylülerin hediyesi',
      metin: 'Köylüler senin için ilin yöresel lezzetinden hazırlamış: {adet} {yemek}.',
      al: 'Hediyeyi al',
      aldin: 'Köylülerin hediyesi heybende: {adet} {yemek}. Afiyet olsun!',
      heybeDolu: 'Köylüler sana hediye hazırlamış ama heyben dolu.',
    },
    unvanAtladin: '🌟 Yeni unvan: {unvan}!',
    isaretler: { yeni: 'Yeni görev var', hazir: 'Teslim edilecek görev var', hediye: 'Hediyen var' },
  },

  itibar: {
    baslik: 'İtibar',
    hayir: 'Hayır puanı',
    unvan: 'Unvanın',
    sonraki: 'Sonraki unvan: {unvan} ({kalan} puan kaldı)',
    enYuksek: 'En yüksek unvana ulaştın.',
    indirim: 'Arastada %{oran} indirim',
    hediye: 'Muhtarlar her ilde bir kez {adet} yöresel yemek hediye eder',
    ayricalikYok: 'Henüz bir ayrıcalığın yok.',
    kazanma: 'Hayır puanı görevlerden, bir ili tamamen arındırmaktan ve halkı bosslardan kurtarmaktan gelir.',
  },

  gunluk: {
    baslik: 'Görev Günlüğü',
    geri: 'Geri dön',
    aktif: 'Üstlendiğin görevler',
    aktifYok: 'Üstlendiğin bir görev yok. Meydanlardaki muhtarlara ve Ahi Babalara uğra.',
    acik: 'Seni bekleyen görevler',
    acikYok: 'Açık bölgelerde bekleyen görev kalmadı.',
    acikSatir: '{il} · {veren}',
    tamam: 'Tamamlanan görevler',
    bolgeSayaci: '{tamam}/{toplam}',
  },

  // Final: Ağrı Dağı'ndaki kale ve Zülmet (plan.md Faz 10).
  final: {
    rozet: 'Zülmet',
    muhurlu: 'Kalenin kapısı Zülmet\'in sihriyle mühürlü. Mührü çözmek için son bölgenin bossu {sonBoss} yenilmeli ({boss}) ve seviyen en az {gerekenSeviye} olmalı (şimdi {seviye}).',
    bossDurumu: { evet: 'yenildi ✓', hayir: 'henüz yenilmedi' },
    acildi: 'Ağrı Dağı\'ndaki kalenin mührü çözüldü! Zülmet seni kalesinde bekliyor.',
    kartBasligi: 'Zülmet\'in kalesi',
    durum: { muhurlu: 'Mühürlü', acik: 'Mührü çözüldü', yenildi: 'Zülmet yenildi ✓' },
    // Üç evreli savaşın evre geçişleri (günlük satırları)
    evreler: {
      2: '{dusman} kara pelerinini açtı; gölgeler etrafında dönmeye başladı!',
      3: '{dusman} üzerindeki sihir çatırdıyor; son gücüyle saldırıyor!',
    },
    evreSahne: { 2: 'Gölge evresi', 3: 'Son direniş' },
    yenildi: 'Zülmet\'in sihri bozuldu!',
  },

  // Oyunun bitiş sahnesi ve 81 ilin özeti.
  bitis: {
    baslik: 'Zulmet Dağıldı',
    hikaye: [
      'Zülmet\'in asası yere düştüğünde Ağrı Dağı\'nın zirvesindeki kara bulutlar dağıldı. Yasak sihir çözüldü; cinler ve ifritler geldikleri karanlığa çekildi, azmış mahlûklar ormanlara ve dağlara döndü.',
      'Kalenin kapısından çıkan {ad}, ovaya indiğinde köylüleri yolların kenarına dizilmiş buldu. Kimi ekmek uzattı, kimi su; çocuklar atının peşinden koştu. Zülmet yenilmişti ama asıl zafer, mazlumun yüzüne dönen tebessümdü.',
      'Kervanlar yeniden yola koyuldu, arastalarda terazi doğru tartmaya, çeşmeler serin serin akmaya başladı. Ahi Babalar çıraklarına {ad}\'ın hikâyesini anlattı: yiğitlik, adaletle; güç, merhametle bir olunca kötülük yenilir.',
    ],
    ozet: 'Yolculuğun özeti',
    seviye: 'Seviye',
    zafer: 'Zafer',
    bayilma: 'Bayılma',
    arinan: 'Arınan il',
    gorev: 'Görev',
    yemek: 'Toplanan yemek',
    basarim: 'Başarım',
    hayir: 'Hayır puanı',
    iller: '81 il',
    ilSatiri: '{il}: %{yuzde}',
    devamNotu: 'Zülmet yenildi ama sihrinin kalıntıları bazı illerde hâlâ dolaşıyor. Dilediğin kadar yolculuğa devam edip kalan illeri arındırabilirsin.',
    devam: 'Yolculuğa devam et',
    yenidenIzle: 'Bitiş sahnesini yeniden izle',
  },

  basarim: {
    baslik: 'Başarımlar',
    kazanildi: '🏅 Başarım: {basarim}',
    sayac: '{kazanilan}/{toplam}',
    kilitli: 'Kilitli',
  },

  ses: {
    ac: 'Sesi aç',
    kapat: 'Sesi kapat',
  },

  nadirlik: { siradan: 'Sıradan', nadir: 'Nadir', efsanevi: 'Efsanevi' },
  yuvaAdlari: { silah: 'Silah', zirh: 'Zırh', aksesuar: 'Kuşak' },

  arasta: {
    baslik: 'Arasta',
    geri: 'Meydana dön',
    selam: 'Esnaf seni güler yüzle karşıladı: "Buyur yiğidim, yolun uzun; heyben hep dolu olsun."',
    al: 'Al',
    fiyat: '{fiyat} akçe',
    akce: 'Kesende {akce} akçe var.',
    heybe: 'Heybe: {dolu} / {toplam} yuva',
    indirim: 'Unvanın sayesinde esnaf sana %{oran} indirim yapıyor.',
    aldin: '{yemek} heybene girdi.',
    neden: {
      akce_yetersiz: 'Akçen yetmiyor.',
      heybe_dolu: 'Heyben dolu.',
    },
  },

  ahi: {
    baslik: 'Ahi Esnafı',
    geri: 'Meydana dön',
    usta: 'Ahi Usta',
    // Esnaf ahlakını (Ahilik) yansıtan selamlar; il plakasına göre biri seçilir.
    selamlar: [
      'Hoş geldin yiğidim. Terazimiz doğru, sözümüz senettir.',
      '"Eline, beline, diline sahip ol" der büyüklerimiz. Buyur, bak beğen.',
      'Kusurlu malı satmak Ahi\'ye yakışmaz. Ne alırsan gönül rahatlığıyla kullan.',
      'Fiyatlarımız herkese aynıdır evlat; ama mazluma yardım eden yiğide gönlümüz daha da açıktır.',
      'Bu kılıcı dövmek üç gün sürdü. Hakkını ver, yeter.',
      'Çırağım senin hikâyeni anlattı. Yolun açık, kolun güçlü olsun.',
      'Yolcu yolunda gerek, ama boş heybeyle değil. Buyur, otur bir soluklan.',
      'Ustam derdi ki: "Kazancın bereketi alın terindedir." Hoş geldin.',
    ],
    yenilenme: 'Tezgâh yenilenmesine {kalan} zafer kaldı.',
    sekmeAl: 'Satın al',
    sekmeSat: 'Sat',
    al: 'Al',
    sat: 'Sat',
    fiyat: '{fiyat} akçe',
    akce: 'Kesende {akce} akçe var.',
    aldin: '{esya} artık senin. Hayırlı olsun!',
    sattin: '{esya} için {akce} akçe aldın.',
    bos: 'Satacak eşyan yok.',
    senin: 'Sende var',
    neden: {
      zaten_var: 'Bu eşya zaten sende.',
      akce_yetersiz: 'Akçen yetmiyor.',
      kusanili: 'Kuşandığın eşyayı satamazsın; önce çıkar.',
    },
  },

  // Yollarda dolaşan, güçlü ekipman satan seyyar tüccar
  tuccar: {
    baslik: 'Seyyar Tüccar',
    geri: 'Yola dön',
    usta: 'Seyyar Tüccar',
    etiket: 'Seyyar tüccar',
    gorundu: '🛍️ Yol kenarında bir seyyar tüccar var! Uzak diyarların mallarını getirmiş.',
    gitti: 'Seyyar tüccar heybesini toplayıp yoluna devam etti.',
    // Esnaf ahlakını yansıtan selamlar; tüccarın tohumuna göre biri seçilir.
    selamlar: [
      'Hayırlı yolculuklar yiğidim! Heybem uzak diyarların ustalarından toplandı.',
      'Yol uzun, yük ağır. Malım sağlamdır; yalnız yol masrafını fiyata kattım.',
      'Bu malları kervanla, dağ dağ taşıdım. Nerede bir yiğit görsem tezgâh açarım.',
      'Ahi ustalarının işi her yerde bilinir. Ben yalnızca taşıdım; eline sağlık, gönlüne rahatlık versin.',
      'Yolda kalan dosta sofra, yiğide silah gerekir. Buyur, bir göz at.',
      'Bir yerde uzun durmam evlat. Beğendiysen şimdi al; kervan yürüyecek.',
    ],
    not: 'Yol masrafı yüzünden fiyatlar Ahi esnafından %50 fazladır.',
    fiyat: '{fiyat} akçe',
    akce: 'Kesende {akce} akçe var.',
    al: 'Al',
    aldin: '{esya} artık senin. Hayırlı olsun!',
    senin: 'Sende var',
    bos: 'Tüccarın tezgâhında sana uygun mal kalmadı.',
    neden: {
      zaten_var: 'Bu eşya zaten sende.',
      akce_yetersiz: 'Akçen yetmiyor.',
    },
  },

  ekipman: {
    baslik: 'Ekipman',
    bos: 'Boş',
    kusan: 'Kuşan',
    cikar: 'Çıkar',
    canta: 'Çanta',
    cantaBos: 'Çantanda eşya yok. Ahi esnafından ya da yollardaki seyyar tüccardan alabilir, bosslardan da kazanabilirsin.',
    kusanildi: '{esya} kuşanıldı.',
    kusanili: 'Kuşanılı',
    seviye: 'Sv {seviye}',
    neden: {
      sinif: 'Sınıfına uygun değil',
      seviye: 'Sv {seviye} gerekir',
    },
  },

  kervansaray: {
    baslik: 'Kervansaray',
    geri: 'Meydana dön',
    selam: 'Kervansarayın serin avlusunda yolcular dinleniyor. Hancı seni güler yüzle misafir etti.',
    dinlen: 'Dinlen',
    dinlendin: 'Dinlendin; canın ve nefesin yerine geldi. Bayılırsan burada kendine geleceksin.',
    sonKervansaray: 'Bayılırsan kendine geleceğin yer: {il}',
    sonKervansarayYok: 'Henüz hiçbir kervansarayda dinlenmedin; bayılırsan bulunduğun ilin meydanında kendine gelirsin.',
    yolculuk: 'Hızlı yolculuk',
    yolculukAciklama: 'Arınmış illerdeki kervansaraylar arasında kervanlarla hemen yolculuk edebilirsin.',
    git: 'Git',
    ucret: '{ucret} akçe',
    vardin: '{il} kervansarayına vardın.',
    neden: {
      arinmamis_baslangic: 'Bu il henüz arınmadı; kervanlar buradan yola çıkmıyor.',
      arinmamis_hedef: 'Arınmadı',
      kilitli_bolge: 'Bölge kilitli',
      akce_yetersiz: 'Akçe yetmiyor',
    },
  },

  // Bölge bossu yenilince gösterilen kısa hikâye (plan.md Faz 7). Ardından rotadaki
  // sıradaki bölgenin haberi (hikayeSonraki), son bölgede ise kalenin haberi (hikayeSon) gelir.
  hikaye: {
    marmara: 'Boğaz\'ın suları duruldu; kayıklar yeniden denize açıldı, halk sevinçle kıyılara indi.',
    ege: 'Yelbegen\'in üç başı da sustu; Ege yolları yeniden kervanlara açıldı, zeytinlikler rahat bir nefes aldı.',
    akdeniz: 'Şahmeran\'ın aklı sihirden arındı; yılanlar mağaralarına çekildi, Akdeniz limanları yeniden şenlendi.',
    ic_anadolu: 'Albastı\'nın gölgesi bozkırdan çekildi; peri bacalarının arasına yeniden güneş doğdu.',
    karadeniz: 'Karakoncolos\'un kışı sona erdi; yaylalara bahar geldi, çay bahçeleri yeşerdi.',
    guneydogu: 'Tepegöz\'ün sihri bozuldu; ovalarda yeniden harman kalktı, kervanlar yola koyuldu.',
    dogu_anadolu: 'Van Gölü\'nün suları sakinleşti; karlı dağların eteklerinde köylüler yeniden ocak tüttürdü.',
  },
  hikayeSonraki: {
    marmara: 'Ama Zülmet\'in sihri Marmara\'ya uzanıyor; Boğaz\'ın sularında bir ejderin gölgesi dolaşıyor.',
    ege: 'Ama Zülmet\'in sihri Ege\'nin zeytinliklerine uzanıyor.',
    akdeniz: 'Toros\'ların ardında ise Şahmeran\'ın gözleri parlıyor.',
    ic_anadolu: 'Bozkırdan ise soğuk bir rüzgâr esiyor.',
    karadeniz: 'Sisli Karadeniz yaylalarından ise bir uğultu yükseliyor.',
    guneydogu: 'Güneydoğunun kızgın ovalarında ise Tepegöz uyanmış.',
    dogu_anadolu: 'Doğunun karlı dağlarında ise Van Gölü\'nün suları kabarıyor.',
  },
  hikayeSon: 'Ağrı Dağı\'nın eteklerinde, Zülmet\'in kalesine giden yolun izleri belirmeye başladı…',

  baslik: {
    devamEt: 'Devam Et',
    yeniOyun: 'Yeni Oyun',
    kayitOzeti: '{ad} · {sinif} · Sv {seviye} · {il}',
    yeniOyunUyarisi: 'Kayıtlı yolculuğun silinecek. Yeni bir oyuna başlamak istediğine emin misin?',
    evet: 'Evet, yeni oyuna başla',
    vazgec: 'Vazgeç',
    kayitYapilamiyor: 'Tarayıcın kayda izin vermiyor; sayfayı kapatınca ilerlemen kaybolur.',
  },

  gezinti: {
    baslikEkrani: 'Başlık ekranına dön',
    ipucu: 'Gitmek istediğin yere dokun ya da yön tuşlarını kullan. Düşmanlara yaklaşınca savaş başlar; meydan güvenlidir.',
    harita: 'Türkiye haritası',
    heybe: 'Heybe',
    ilBilgisi: 'İl bilgisi',
    yonTuslari: 'Yön tuşlarını göster ya da gizle',
    yukari: 'Yukarı yürü',
    asagi: 'Aşağı yürü',
    sola: 'Sola yürü',
    saga: 'Sağa yürü',
    arinma: 'Arınma %{yuzde}',
    cesme: 'Çeşmenin serin suyuyla yüzünü yıkadın.',
    gunluk: 'Görev günlüğü ve başarımlar',
    girisAfisi: '{il}',
    fark: '{dusman} seni fark etti!',
    farkKalabalik: '{sayi} yaratık birden saldırıya geçti!',
    alanEtiketi: '{il} il haritası',
    kisayollar: 'Klavye kısayolları',
    takip: '👣 {dusman} peşine takıldı! Kolay kolay bırakmaz; meydana sığın ya da savaş.',
    takipciRozeti: 'İz sürer: peşine takılır',
    bekciRozeti: 'Yakına gelirsen saldırır',
    kayitsizRozeti: 'Kendi hâlinde: peşine düşmez, üstüne varırsan dövüşür',
    yankesiciRozeti: 'Yankesici: kesene göz dikti',
    yankesici: '🗡️ Bir yankesici kesene göz dikti! Savaş ya da meydana sığın.',
    yankesiciIkili: '🗡️ İki yankesici kesene göz dikti! Savaş ya da meydana sığın.',
    yankesiciGitti: 'Yankesici izini kaybetti, söylenerek çekip gitti.',
  },

  // Savaş kısayol yuvaları (1–4 tuşları)
  kisayol: {
    baslik: 'Savaş Kısayolları',
    aciklama: 'Savaşta sıra sendeyken 1–4 tuşlarıyla ya da yuvaya dokunarak kullanılır. Bir yuvaya dokunup içine yetenek, yemek, Saldır ya da Kaç koyabilirsin.',
    bos: 'Boş',
    yuvaEtiketi: '{tus}. yuva: {ad}',
    sec: '{tus}. yuvaya ne konsun?',
    bosalt: 'Yuvayı boşalt',
    baskaYuvada: '{tus}. yuvada (buraya taşınır)',
    duzenle: 'Yuvaları düzenle',
    duzenleBitti: 'Düzenlemeyi bitir',
    siraSende: 'Sıra sende · 1–4',
    bekle: 'Bekle…',
    kullanilamaz: 'Bu yuva şu an kullanılamaz.',
  },

  // Klavye kısayolları penceresi
  klavye: {
    baslik: '⌨️ Klavye Kısayolları',
    kapat: 'Kapat',
    gruplar: [
      { baslik: 'Gezinti', satirlar: [['W A S D / Oklar', 'Yürü'], ['M', 'Türkiye haritası'], ['B', 'Heybe (çanta)'], ['K', 'Karakter'], ['G', 'Görev günlüğü'], ['L', 'İl bilgisi'], ['?', 'Bu pencere']] },
      { baslik: 'Açık ekranlarda', satirlar: [['Esc', 'Geri dön'], ['Aynı tuş', 'Ekranı kapatıp gezintiye dön']] },
      { baslik: 'Savaş', satirlar: [['1 2 3 4', 'Kısayol yuvasını kullan (sıra sendeyken)'], ['Esc', 'Alt menüden çık'], ['Enter', 'Seçili düğme']] },
    ],
  },

  // İllerin gerçek büyüklüğü ve kalabalığı
  cografya: {
    yuzolcumu: 'Yüzölçümü',
    nufus: 'Nüfus',
    yogunluk: 'Yoğunluk',
    alanDegeri: '{deger} km² · 81 il içinde {sira}.',
    nufusDegeri: '{deger} kişi · 81 il içinde {sira}.',
    yogunlukDegeri: '{deger} kişi/km²',
    haritaNotu: 'İl haritası gerçek yüzölçümüyle orantılıdır ({genislik} × {yukseklik} karo); evler ve meydandaki halk nüfusla artar.',
    ozellikler: {
      en_genis: '🏞️ Türkiye\'nin yüzölçümü en büyük ili',
      ilk_bes_genis: '🏞️ Yüzölçümünde ilk beş',
      en_kucuk: '📐 Türkiye\'nin yüzölçümü en küçük ili',
      en_kalabalik: '🏙️ Türkiye\'nin en kalabalık ili',
      ilk_bes_kalabalik: '🏙️ Nüfusta ilk beş',
      en_az_nufus: '🌾 Türkiye\'nin nüfusu en az ili',
      en_yogun: '👥 Nüfus yoğunluğu en yüksek il',
      en_seyrek: '🏔️ Nüfus yoğunluğu en düşük il',
    },
  },

  ilEkrani: {
    haritayaDon: 'Haritaya dön',
    ildeGez: 'İlde Gez',
    gezintiyeDon: 'Gezintiye dön',
    heybe: 'Heybe',
    karakter: 'Karakter',
    seviye: 'Düşman seviyesi',
    yemek: 'Meşhur yemeği',
    arinma: 'Arınma',
    arinmaIpucu: 'Her zafer ili %12–18 arındırır. %100 olunca il arınmış sayılır.',
    arinmis: '✓ Bu il Zülmet\'in sihrinden arındı. Keşfe çıkıp tecrübe kazanmaya devam edebilirsin.',
    canAz: 'Canın azaldı. Keşfe çıkmadan önce heybenden bir şeyler yiyebilirsin.',
    akce: '{akce} akçe',
  },

  envanter: {
    baslik: 'Heybe',
    geri: 'Geri dön',
    yuva: '{dolu} / {toplam} yuva',
    bos: 'Heyben boş. Düşmanları yendikçe illerin yöresel yemeklerini toplarsın.',
    ye: 'Ye',
    etki: '+{miktar} {tur}',
    doluCan: 'Canın zaten dolu.',
    doluNefes: 'Nefesin zaten dolu.',
    yedin: '{yemek} yedin: +{miktar} {tur}.',
    yeAciklama: '{yemek} ye',
  },

  harita: {
    baslikEkrani: 'Başlık ekranına dön',
    konum: 'Bulunduğun il',
    yakinlastir: 'Yakınlaştır',
    uzaklastir: 'Uzaklaştır',
    ortala: 'Bulunduğun ile odaklan',
    tumu: 'Tüm haritayı göster',
    bolge: 'Bölge',
    seviye: 'Düşman seviyesi',
    seviyeDegeri: 'Sv {en_az}–{en_cok}',
    yemek: 'Meşhur yemeği',
    arinma: 'Arınma',
    buradasin: 'Buradasın.',
    git: 'Buraya git',
    kapat: 'Kapat',
    ileGir: 'İlde gez',
    olanaklar: 'Olanaklar',
    kervansaray: '🏨 Kervansaray',
    ahi: '⚒️ Ahi esnafı',
    gorev: '📜 Görev: {verenler}',
    varis: 'Yeni konum: {il}',
    ipucu: 'Bir ile dokunarak bilgilerini gör. Parmağınla kaydır, iki parmakla yakınlaştır.',
    lejant: {
      kilitli: 'Kilitli',
      acik: 'Açık',
      bulunulan: 'Bulunduğun il',
      arinmis: 'Arınmış',
    },
    denizler: {
      karadeniz: 'Karadeniz',
      akdeniz: 'Akdeniz',
      ege: 'Ege Denizi',
      marmara: 'Marmara',
    },
  },

  statAdlari: {
    can: 'Can',
    nefes: 'Nefes',
    guc: 'Güç',
    savunma: 'Savunma',
    ceviklik: 'Çeviklik',
  },

  dusmanTurleri: {
    hayvan: 'Hayvan',
    cin: 'Cin',
    ifrit: 'İfrit',
    hortlak: 'Hortlak',
    dev: 'Dev',
    insan: 'Yol haramisi',
    boss: 'Boss',
  },

  yeniOyun: {
    baslik: 'Yeni Oyun',
    geri: 'Başlık ekranına dön',
    adEtiketi: 'Yiğidin adı',
    adIpucu: 'Boş bırakırsan adın Alp olur.',
    sinifBasligi: 'Yolunu seç',
    sinifSec: '{sinif} sınıfını seç',
    secimYok: 'Yola çıkmak için bir sınıf seç.',
    baslat: 'Yola Çık',
    yolculukBasliyor: 'Yolculuğun {bolge} bölgesinde, {il} ilinde başlıyor. Diğer bölgeler bossları yendikçe açılacak.',
  },

  karakter: {
    baslik: 'Karakter',
    geri: 'Geri dön',
    seviye: 'Sv {seviye}',
    xp: 'Tecrübe (XP)',
    xpDegeri: '{xp} / {gereken} XP',
    statlar: 'Statlar',
    statPuani: 'Dağıtılacak stat puanı: {puan}',
    statPuaniYok: 'Seviye atladıkça dağıtabileceğin stat puanları kazanırsın.',
    puanVer: '{stat} statına 1 puan ver (+{artis})',
    yetenekler: 'Yetenekler',
    yetenekNefes: '{nefes} nefes',
    yetenekKilitli: 'Sv {seviye} olunca açılır',
    akce: 'Akçe',
    hayir: 'Hayır',
    ustCubukDugmesi: 'Karakteri aç: {ad}, seviye {seviye}',
  },

  savas: {
    baslik: 'Savaş',
    seviye: 'Sv {seviye}',
    saldir: 'Saldır',
    yetenek: 'Yetenek',
    yemek: 'Yemek',
    kac: 'Kaç',
    geri: 'Geri',
    heybeBos: 'Heybende yemek yok.',
    kacilamaz: 'Bu mahlûktan kaçılamaz.',
    nefesYetersiz: 'Nefesin yetmiyor.',
    sahne: {
      siyrildi: 'Sıyrıldı',
      guclendi: 'Güçlendi!',
      dustu: 'Püskürtüldü',
    },
    hedef: 'Hedef',
    hedefSec: 'Vuracağın yaratığı seç',
    // Aynı türden birden fazla yaratıkta ad numaralanır: "Aç kurt 2"
    ve: ' ve ',
    etkiler: {
      sofra: '🍽️ Zafer sofrası ({kalan})',
      savunma: '🛡️ Korunma ({kalan})',
      guclenme: '💪 Güç ({kalan})',
      kritik: '🦅 Keskin göz ({kalan})',
      zayiflatma: '😨 Ürkmüş ({kalan})',
    },
    gunluk: {
      baslangic: '{dusman} (Sv {seviye}) yolunu kesti!',
      baslangicGrup: '{dusmanlar} birlikte saldırıya geçti! Hepsi aynı anda vuruyor; kalabalıktan kaçmak daha zor.',
      kacisBasarisizGrup: 'Kaçamadın! Yaratıklar yolunu kesti.',
      grupZafer: 'Saldıran yaratıkların hepsini püskürttün!',
      saldiri: 'Saldırdın: {hasar} hasar.',
      yetenekHasar: '{yetenek}: {hasar} hasar.',
      kritik: 'Kritik vuruş!',
      ekHasar: 'Sihri sarsıldı!',
      dusmanKacindi: '{dusman} hamlenden sıyrıldı.',
      yetenekSifa: '{yetenek}: {miktar} can toparladın.',
      yetenekSavunma: '{yetenek}: düşmanın sonraki {sure} hamlesinde daha az hasar alacaksın.',
      yetenekGuclenme: '{yetenek}: sonraki {sure} saldırın daha güçlü olacak.',
      yetenekKritik: '{yetenek}: sonraki {sure} saldırında kritik vuruş şansın arttı.',
      yemek: '{yemek} yedin: {miktar} {tur} yeniledin.',
      dusmanSaldiri: '{dusman} saldırdı: {hasar} hasar aldın.',
      ozelHamle: '{dusman} — {hamle}! {hasar} hasar aldın.',
      zayiflatma: '{dusman} — {hamle}! Sonraki {sure} saldırında gücün azalacak.',
      oyuncuKacindi: '{dusman} saldırdı ama hamleden ustalıkla sıyrıldın.',
      ozelKacindi: '{dusman} — {hamle}! Ama hamleden ustalıkla sıyrıldın.',
      korundu: 'Duruşun hasarı azalttı.',
      kacisBasarili: 'Geri çekilip yoluna devam ettin.',
      kacisBasarisiz: 'Kaçamadın! {dusman} yolunu kesti.',
      evre: '{dusman} üzerindeki sihir kabardı; daha da güçlendi!',
      yenilgi: 'Gözlerin karardı, bayıldın…',
      gezgin: {
        zorlu: '{dusman} bu diyarın düşmanlarından çok daha güçlü, ama yenilmez değil. Dikkatli dövüş!',
        kesilemez: '{dusman} öyle güçlü ki kılıç zırhına zor işliyor! Kaçmak en akıllıcası olabilir.',
      },
    },
    // Yenilen düşmanlar ölmez: kaçar, dağılır ya da sihri bozulur (plan.md Bölüm 2).
    dagilma: {
      hayvan: '{dusman} geri çekilip kaçtı.',
      cin: '{dusman} üzerindeki sihir bozuldu, dağılıp gitti.',
      ifrit: '{dusman} üzerindeki sihir bozuldu, dumana dönüşüp dağıldı.',
      hortlak: '{dusman} sisin içinde dağılıp kayboldu.',
      dev: '{dusman} üzerindeki sihir bozuldu; sessizce çekip gitti.',
      insan: '{dusman} sopasını bırakıp tabana kuvvet kaçtı; kesesi geride kaldı.',
      boss: '{dusman} üzerindeki sihir bozuldu!',
    },
    sonuc: {
      zafer: 'Zafer!',
      yenilgi: 'Bayıldın',
      kacis: 'Geri Çekildin',
      xp: '+{xp} XP kazandın.',
      bayilma: '{il} merkezinde kendine geldin. Halk seni misafir etti; canın ve nefesin yerine geldi.',
      bayilmaKervansaray: '{il} kervansarayında kendine geldin. Hancı seni misafir etti; canın ve nefesin yerine geldi.',
      akceKaybi: 'Kesenden {akce} akçe düşmüş.',
      calinanAkce: '🗡️ Yankesici fırsatı kaçırmadı: kesenden {akce} akçe aşırdı.',
      kacis: 'Canını kurtardın; bu karşılaşmadan ödül yok.',
      seviyeAtladin: '🎉 Seviye atladın! Artık Sv {seviye}.',
      statPuaniKazandin: 'Dağıtılacak {puan} stat puanın var.',
      yeniYetenek: '✨ Yeni yetenek: {yetenek}',
      arinma: 'İl %{artis} arındı (şimdi %{yuzde}).',
      arindi: '🌿 {il} Zülmet\'in sihrinden tamamen arındı!',
      akce: '+{akce} akçe kazandın.',
      yemek: '{ikon} {yemek} buldun!',
      yemekSigmadi: '{ikon} {yemek} buldun ama heyben dolu, yanına alamadın.',
      esya: '{ikon} {esya} ({nadirlik}) kazandın! Karakter ekranından kuşanabilirsin.',
      hayir: '+{hayir} Hayır puanı: halk sana minnettar.',
      gorevIlerlemesi: '📜 {gorev}: {mevcut}/{hedef}',
      gorevHazir: '📜 "{gorev}" tamamlanmaya hazır; görevi verene dön.',
      devam: 'Devam et',
      karakteriAc: 'Karakterine bak',
    },
  },

  seyahatEngeli: {
    ayni_il: 'Zaten buradasın.',
    kilitli_bolge: '{bolge} bölgesi henüz kilitli. Yollar Zülmet\'in sihriyle kapalı.',
    komsu_degil: '{hedef}, bulunduğun il {konum} ile komşu değil. Yalnızca komşu illere gidebilirsin.',
  },
};
